/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ijexnniqkpfigarfvbrv";
export const publicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqZXhubmlxa3BmaWdhcmZ2YnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3OTMxMDUsImV4cCI6MjA3NTM2OTEwNX0.SphF2tf8jLTKa6z1ihpFvo-BhCa5LG6XKocHc-ET_S4";
